### ISSUE TITLE
Are you sure about the name?

### ISSUE THREAD

**Issue by johschmitz** [pfirsich/cli.hpp#1]
There is a well established project (over 900 stars) with the same name in the exact same domain:

https://github.com/muellan/clipp

Are you sure that you want to create such a naming collision? For the good health of the community please reconsider your decision.

**Comment by pfirsich** [comment]
If I had been aware of that, I would have chosen a different name. Thanks for pointing it out. I do use my clipp library in a couple of my own projects already, so I'd rather not have the hassle of changing the name.

> For the good health of the community please reconsider your decision.

May I ask what exactly you are afraid of? In what way would the health of the community be threatened? Consider that my project has 0 stars and is used by nobody except me.

**Comment by johschmitz** [comment]
In the end of cause it is up to you but causing naming conflicts like this is usually seen somewhere on the spectrum between annoying to outright hostile depending on whom you ask. In my opinion doing some sanity check regarding the name (like googling) before publication is standard best practice.

Let's just assume that your library will be used by some people (why should you publish it otherwise after all) and then they would want to add Conan recipes for it to https://github.com/conan-io/conan-center-index, now it is just not possible because https://github.com/conan-io/conan-center-index/tree/master/recipes/clipp is already taken. So you see you are creating all kinds of problems for other people down the line. It just makes little sense to combine the "friendly" act of publishing free(?, btw: LICENSE file is missing) open source software in combination with this kind of hostile act that makes it difficult for other people to use it.

As I said, in the end it is up to you how you want to behave, just take this as a "friendly feedback from the Internet". In the end maybe you could at least change the name of the repository slightly with a prefix/postfix or add a hint to the README.md such that it is not so easy to confuse it with the other clipp when searching for "clipp parser" or "clipp C++" or similar keywords on Google.

**Comment by pfirsich** [comment]
Usually I do check the name, but I guess this time I didn't? I did not forget the LICENSE. I stopped adding a license to my project on purpose a while ago. I don't care much about people using my stuff anymore. My stuff is mainly on here, so I can look at it whenever and wherever I go and so that other people can get ideas, if they want to. This is a great example of open sourcing your code (in the FOSS-sense - including a license) being extra trouble for no real gain.

I think calling it outright hostile (multiple times even) is not "friendly feedback" anymore, sorry. Actually, it is **very** weird. You need to relax. I just forgot to check if the name is already in use.

I'll think about changing the name.

**Comment by johschmitz** [comment]
Sorry if I formulated it a bit too harsh for your understanding I did not meant to stress you out or hurt your feeling or anything personal like that. I did not meant to say that the action was intentionally hostile from your side (sounds like you understood what I wrote like that) but that it is an action that can potentially be seen as hostile from the developer community because it can create trouble for some people and or technical systems.
